configfile : "../config/config.yaml"
import pandas as pd

samples = pd.read_csv(config["samples"],index_col="sample", sep ='\t')
IDS=[s for s in list(samples.index)]
all_fq = [ID + "_1" for ID in IDS] + [ID + "_2" for ID in IDS]
wildcard_constraints:
    sample= config["sample_regex"] #"hcc.+_.+_.+",

#include: "rules/bowtie.smk"
#include: "rules/samtools.smk"
include: "rules/qc.smk"
include: "rules/denovo.smk"
include: "rules/star.smk"
include: "rules/featureCounts.smk"


rule all:
    input:
        "../results/denovo_assembly/trinity.Trinity.fasta", #
        # "../results/counts/kallisto/hcc1395_tumor_rep3/abundance.tsv",
        #"../results/fastq/merged/merged_r2.fq",
        #expand("../results/fasta/{sample}.fa", sample=IDS),
        "../results/qc/multiqc_report.html",
        expand("../results/counts/featurecounts/{sample}.txt", sample=IDS),
        expand("../results/counts/rsem/{sample}.genes.results", sample=IDS)








