configfile : "../config/config.yaml"
import pandas as pd

samples = pd.read_csv(config["samples"],index_col="sample", sep ='\t')
IDS=[s for s in list(samples.index)]
all_fq = [ID + "_1" for ID in IDS] + [ID + "_2" for ID in IDS]
wildcard_constraints:
    sample= "hcc.+_.+_.+", #"[^\/]",#
    #folder ="\w+"

#include: "rules/bowtie.smk"
#include: "rules/samtools.smk"
include: "rules/qc.smk"
include: "rules/denovo.smk"


rule all:
    input:
        "../results/denovo_assembly/trinity.fasta",
        #"../results/fastq/merged/merged_r2.fq",#
        #expand("../results/fasta/{sample}.fa", sample=IDS),
        "../results/qc/multiqc_report.html",
        expand("../results/counts/{sample}.txt", sample=IDS)








