samples: "../resources/samples.tsv"

# directories
references: "../resources/references/references.fa"
kraken_db: "../resources/kraken_db"
contamination_reference: "../resources/references/flu.fa"


# parameters:
decontamination: "True"

bowtie2:
  local: "--local" #"--local" or " "
  ma: "0" #scores can be configured with the --ma (match bonus)

multiqcparam: "-f"

trimmomatic:
  trailing: "20"
  illuminaclip:
    file: "../resources/adapters/TruSeq3-PE.fa"
    seedMissmatches: '2'
    palindromeClipThreshold: '30'
    simpleClipThreshold: '10'


tree:
  method: "iqtree" #{fasttree,raxml,iqtree}

consenus:
  q: 20 #Minimum quality score threshold to count base

variability:
  l: 2 #Window length

skip_trimming: 'False'
skip_fastQC: 'False'
skip_qualimap: 'False'

