# directories
samples: "../resources/samples.tsv"
reference: "../resources/reference/chromosome.fa"
annotation: "../resources/reference/annotation.gff3"
adapters: "../resources/adapters"
sample_regex: "hcc.+_.+_.+"

# parameters:
skip_trimming: 'False'
skip_fastQC: 'False'
skip_qualimap: 'False'

bowtie2:
  local: "--local" #"--local" or " "
  ma: "0" #scores can be configured with the --ma (match bonus)

multiqcparam: "-f"

trimmomatic:
  trailing: "20"
  illuminaclip:
    file: "../resources/adapters/TruSeq3-PE.fa"
    seedMissmatches: '2'
    palindromeClipThreshold: '30'
    simpleClipThreshold: '10'
